name: platform-ef

services:
  platform-ef-redis:
    image: redis:7-alpine
    container_name: platform-ef-redis
    restart: unless-stopped
    command: ["redis-server","--appendonly","yes","--save","60","1000","--requirepass","fingate!234"]
    networks:
      platform-ef-network:
        aliases:
          - platform-ef-redis
      edge: {}
    labels:
      - traefik.enable=true
      - traefik.docker.network=edge
      # 6379(TLS) 포트에서 SNI로 분기
      - traefik.tcp.routers.redis-platform-ef.entrypoints=redis-tls
      - traefik.tcp.routers.redis-platform-ef.rule=HostSNI(`ef.redis.fingate.kr`)
      - traefik.tcp.routers.redis-platform-ef.tls=true
      - traefik.tcp.services.redis-platform-ef.loadbalancer.server.port=6379

  platform-ef-rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: platform-ef-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: pf_ef_admin
      RABBITMQ_DEFAULT_PASS: pf_ef_admin
    volumes:
    - /home/fingate/docker/volumes/rabbitmq/platform/ef/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    - /home/fingate/docker/volumes/rabbitmq/platform/ef/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      platform-ef-network:
        aliases:
          - platform-ef-rabbitmq
      edge: {}
    labels:
      - traefik.enable=true
      - traefik.docker.network=edge
      # 5671(TLS) 포트에서 SNI로 분기
      - traefik.tcp.routers.amqp-platform-ef.entrypoints=amqp-tls
      - traefik.tcp.routers.amqp-platform-ef.rule=HostSNI(`ef.mq.fingate.kr`)
      - traefik.tcp.routers.amqp-platform-ef.tls=true
      - traefik.tcp.services.amqp-platform-ef.loadbalancer.server.port=5672
      # (선택) RabbitMQ UI는 HTTP 80에서 Host로 분기
      - traefik.http.routers.rabbitui-platform-ef.entrypoints=web
      - traefik.http.routers.rabbitui-platform-ef.rule=Host(`ef-web.mq.fingate.kr`)
      - traefik.http.services.rabbitui-platform-ef.loadbalancer.server.port=15672

networks:
  edge:
    external: true
  platform-ef-network:
    external: true

