name: platform-ef-develop

# =========================================================================
# DEVELOP 환경 (develop 브랜치)
# =========================================================================

services:
  # -------------------------
  # Front Application - Develop
  # -------------------------
  platform-ef-develop-web:
    image: spa-nginx:1.0.8
    container_name: platform-ef-develop-web
    restart: unless-stopped
    volumes:
      - /home/fingate/docker/volumes/platform/ef-develop/front/web:/usr/share/nginx/html:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.platform-ef-develop-web.rule=Host(`eventflow-dev.fingate.kr`)
      - traefik.http.routers.platform-ef-develop-web.entrypoints=web
      - traefik.http.services.platform-ef-develop-web.loadbalancer.server.port=80
      - traefik.docker.network=edge
    networks: [edge, monitor]

  platform-ef-develop-web-metrics:
    image: nginx/nginx-prometheus-exporter:1.3.0
    container_name: platform-ef-develop-web-metrics
    restart: unless-stopped
    depends_on: [platform-ef-develop-web]
    command: ["-nginx.scrape-uri=http://platform-ef-develop-web:8081/stub_status"]
    networks: [monitor]

networks:
  edge:
    external: true
  monitor:
    external: true
